### ISSUE TITLE
What‘s the surface data (areacella.nc) in your job.py ?

### ISSUE THREAD

**Issue by chenzheng1996** [RamAlkama/FutureVegBioph#1]

**Comment by RamAlkama** [comment]
areacella.nc is a grid area file that was generated with cdo 
cdo gridarea Netcdf_file_at_0.05deg.nc areacella.nc

**Comment by chenzheng1996** [comment]
What's the variable name of the surface data (variable like precipitation or LAI) ?  Can you share some data, i m learning the article to research the temperature rising due to vegetation but when reading the code i dont konw the data meaning in your code.  Thanks for your reply.
